/**
 * CMS — visual page builder.
 *
 * A page (site_pages row) holds an ordered list of blocks. Each block is one
 * of:
 *   - text   — markdown body
 *   - image  — a media URL + alt
 *   - custom — a widget built by the user or generated by the AI block
 *              builder (form, interactive map, YouTube embedder, Instagram
 *              gallery, etc.). Custom blocks carry a `kind` + `config` and
 *              are rendered by a safe, allowlisted renderer — the AI only
 *              produces the CONFIG, never raw HTML.
 */

export type CmsBlockKind = "text" | "image" | "custom" | "section" | "columns";

/** Per-block styling — kept small and declarative, applied via inline styles
 * and a few utility classes (no per-block CSS bloat). */
export interface CmsBlockStyle {
  padding?: "none" | "sm" | "md" | "lg";
  align?: "left" | "center" | "right";
  bg?: string;
  /** Background image (rows/sections) or video (sections) behind content. */
  bgImage?: string;
  bgVideo?: string;
  color?: string;
  width?: "full" | "wide" | "half" | "third";
  /** Page-level layout: full-bleed rows vs a boxed centered column. */
  boxed?: boolean;
  /** Float an image block so neighboring text wraps around it. */
  float?: "none" | "left" | "right";
}

export interface CmsBlock {
  id: string;
  kind: CmsBlockKind;
  /** Custom widget type — one of the known builders below, or "ai". */
  custom?: "form" | "map" | "youtube" | "instagram" | "embed" | "note" | "ai";
  /** Raw text / markdown for text blocks. */
  content?: string;
  /** When true, text-block content is authored/rendered as raw HTML. */
  html?: boolean;
  /** Image URL for image blocks. */
  url?: string;
  alt?: string;
  /** Widget config (safe JSON, rendered by the allowlisted renderers). */
  config?: Record<string, unknown>;
  /** Section / columns container — holds child blocks (one level deep). */
  children?: CmsBlock[];
  /** Columns block: number of columns (2 | 3 | 4); children flow left→right. */
  cols?: number;
  /** Per-block styling controls (Elementor-style, kept lean). */
  style?: CmsBlockStyle;
}

export interface CmsPage {
  id: string;
  tenant_id: string;
  workspace_id: string | null;
  client_id: string | null;
  title: string;
  slug: string;
  blocks: CmsBlock[];
  is_published: boolean;
  published_at: string | null;
  created_at: string;
  updated_at: string;
  /** Content model: 'page' | 'blog_archive' | 'blog_post'. */
  kind?: "page" | "blog_archive" | "blog_post";
  /** Grouping label, e.g. 'services' for pages, 'company news' for posts. */
  category?: string | null;
}

const BLOCK_ID_PREFIX = "blk_";

export function newBlockId(): string {
  return BLOCK_ID_PREFIX + Math.random().toString(36).slice(2, 10) + Date.now().toString(36);
}

export function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 60) || "page";
}

// ============================================================================
// Rendering
// ============================================================================

/** Escape a value for safe HTML attribute embedding. */
function esc(v: unknown): string {
  return String(v ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function markdownToHtml(md: string): string {
  // Minimal, safe subset: paragraphs, ##/### headings (even when a heading
  // follows a paragraph with only a single newline), **bold**, *italic*,
  // links, and line breaks. Images on their own line become figures: the
  // FIRST one is a centered hero, the rest float left/right alternating so
  // text wraps around them (never stacked). NOT a full markdown engine —
  // content is authored in the builder, and we never execute raw HTML.
  const lines = md.split(/\r?\n/);
  const out: string[] = [];
  let para: string[] = [];
  let imgCount = 0;
  const flush = () => {
    if (para.length > 0) {
      out.push(`<p>${para.join("<br />")}</p>`);
      para = [];
    }
  };
  for (const raw of lines) {
    const line = raw.trim();
    const img = line.match(/^!\[([^\]]*)\]\((https?:\/\/[^)\s]+)\)$/);
    if (img) {
      flush();
      imgCount += 1;
      const cls =
        imgCount === 1
          ? "cms-blog-img cms-hero-img"
          : `cms-blog-img ${imgCount % 2 === 0 ? "cms-float-left" : "cms-float-right"}`;
      out.push(
        `<figure class="${cls}"><img src="${esc(img[2])}" alt="${esc(img[1] || "Blog image")}" loading="lazy" /></figure>`
      );
      continue;
    }
    const h = line.match(/^(#{1,3})\s+(.+)$/);
    if (h) {
      flush();
      out.push(`<h${h[1].length}>${esc(h[2])}</h${h[1].length}>`);
      continue;
    }
    if (!line) {
      flush();
      continue;
    }
    const styled = line
      .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
      .replace(/\*([^*]+)\*/g, "<em>$1</em>")
      // Inline image inside a paragraph → plain inline <img>, not floated.
      .replace(/!\[([^\]]*)\]\((https?:\/\/[^)\s]+)\)/g, '<img src="$2" alt="$1" loading="lazy" />')
      .replace(/\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)/g, '<a href="$2" target="_blank" rel="noopener">$1</a>');
    para.push(styled);
  }
  flush();
  return out.join("\n");
}

function youtubeEmbed(url: string): string {
  const m = url.match(/(?:youtube\.com\/(?:watch\?v=|embed\/|shorts\/)|youtu\.be\/)([\w-]{6,})/);
  const id = m?.[1] ?? "";
  if (!id) return `<p class="cms-block-error">Invalid YouTube URL</p>`;
  return `<div class="cms-embed cms-youtube"><iframe src="https://www.youtube-nocookie.com/embed/${esc(id)}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>`;
}

function instagramEmbed(url: string): string {
  // Use the post URL in an iframe via instagram embed endpoint; fall back to a
  // styled link card when the URL is invalid.
  const valid = /^https:\/\/www\.instagram\.com\/p\/[\w-]+\/?/.test(url);
  if (!valid) return `<p class="cms-block-error">Invalid Instagram post URL (use https://www.instagram.com/p/...) — the app can also embed entire feeds/galleries as links.</p>`;
  return `<div class="cms-embed cms-instagram"><iframe src="https://www.instagram.com/${esc(url.replace(/^https:\/\/www\.instagram\.com\//, ""))}embed" title="Instagram post" frameborder="0" scrolling="no" allowtransparency></iframe></div>`;
}

function mapEmbed(config: Record<string, unknown>): string {
  const q = esc(config.query ?? "Toronto, Ontario");
  return `<div class="cms-embed cms-map"><iframe title="Interactive map" src="https://www.google.com/maps?q=${encodeURIComponent(String(q))}&output=embed" frameborder="0" allowfullscreen loading="lazy"></iframe></div>`;
}

function formEmbed(pageId: string, blockId: string, config: Record<string, unknown>): string {
  const fields = Array.isArray(config.fields) ? config.fields : ["name", "email", "message"];
  const btn = esc(config.buttonText ?? "Submit");
  const isNewsletter = config.newsletter === true;
  const inputs = fields
    .map((f) => {
      const name = esc(f);
      const label = esc(String(f).replace(/_/g, " "));
      const type = name === "email" ? "email" : "text";
      const isTextarea = name === "message" || name === "comments";
      return isTextarea
        ? `<label class="cms-field"><span>${label}</span><textarea name="${name}" rows="3" required></textarea></label>`
        : `<label class="cms-field"><span>${label}</span><input type="${type}" name="${name}" required /></label>`;
    })
    .join("");
  const consent = isNewsletter
    ? `<label class="cms-field cms-consent"><input type="checkbox" name="consent" required /> I agree to receive emails and understand I can unsubscribe anytime.</label>`
    : "";
  return `<form class="cms-form" data-page="${esc(pageId)}" data-block="${esc(blockId)}" action="/api/cms/forms" method="POST">${inputs}${consent}<button type="submit" class="cms-btn">${btn}</button><p class="cms-form-status" role="status"></p></form>`;
}

const PADDING_CLASSES: Record<string, string> = {
  none: "",
  sm: "cms-pad-sm",
  md: "cms-pad-md",
  lg: "cms-pad-lg",
};

const WIDTH_CLASSES: Record<string, string> = {
  full: "",
  wide: "cms-w-wide",
  half: "cms-w-half",
  third: "cms-w-third",
};

/** Build the wrapper element + inline styles for a block's style config. */
function blockWrapper(block: CmsBlock): string {
  const s = block.style ?? {};
  const inline: string[] = [];
  if (s.bg) inline.push(`background:${s.bg}`);
  if (s.color) inline.push(`color:${s.color}`);
  const styleAttr = inline.length ? ` style="${inline.join(";")}"` : "";
  return `<div class="cms-block ${PADDING_CLASSES[s.padding ?? "none"]} ${WIDTH_CLASSES[s.width ?? "full"]} cms-align-${s.align ?? "left"}"${styleAttr}>`;
}

/**
 * Render a block to HTML. Text/image are internal; custom widgets go through
 * the allowlisted renderers — the AI only supplies CONFIG, never markup.
 */
export function renderBlockHtml(block: CmsBlock, pageId?: string): string {
  switch (block.kind) {
    case "text":
      // HTML mode outputs the authored markup directly (tenant editors only).
      return block.html
        ? `${blockWrapper(block)}<div class="cms-text">${block.content ?? ""}</div></div>`
        : `${blockWrapper(block)}<div class="cms-text">${markdownToHtml(block.content ?? "")}</div></div>`;
    case "image": {
      const f = block.style?.float;
      const floatClass =
        f === "left" || f === "right" ? ` cms-float-${f}` : "";
      return block.url
        ? `${blockWrapper(block)}<figure class="cms-image${floatClass}"><img src="${esc(block.url)}" alt="${esc(block.alt ?? block.content ?? "")}" loading="lazy" /><figcaption>${esc(block.alt ?? "")}</figcaption></figure></div>`
        : "";
    }
    case "section": {
      const s = block.style ?? {};
      const inline: string[] = [];
      if (s.bg) inline.push(`background:${s.bg}`);
      if (s.color) inline.push(`color:${s.color}`);
      if (s.bgImage) inline.push(`background-image:url('${esc(s.bgImage)}');background-size:cover;background-position:center`);
      if (s.bgVideo) inline.push(`position:relative`);
      const styleAttr = inline.length ? ` style="${inline.join(";")}"` : "";
      const inner = (block.children ?? []).map((c) => renderBlockHtml(c, pageId)).join("\n");
      const boxed = s.boxed === false ? "cms-section-bleed" : "";
      const bgVideo = s.bgVideo
        ? `<video class="cms-section-bg" src="${esc(s.bgVideo)}" autoplay muted loop playsinline></video>`
        : "";
      return `<section class="cms-section ${PADDING_CLASSES[s.padding ?? "md"]} ${boxed}"${styleAttr}>${bgVideo}<div class="cms-section-inner">${inner || ""}</div></section>`;
    }
    case "columns": {
      const s = block.style ?? {};
      const inline: string[] = [];
      if (s.bg) inline.push(`background:${s.bg}`);
      if (s.color) inline.push(`color:${s.color}`);
      if (s.bgImage) inline.push(`background-image:url('${esc(s.bgImage)}');background-size:cover;background-position:center`);
      const styleAttr = inline.length ? ` style="${inline.join(";")}"` : "";
      const cols = [2, 3, 4].includes(block.cols ?? 2) ? (block.cols as number) : 2;
      const inner = (block.children ?? []).map((c) => renderBlockHtml(c, pageId)).join("\n");
      const boxed = s.boxed === false ? "cms-section-bleed" : "";
      return `<div class="cms-columns cms-columns-${cols} ${PADDING_CLASSES[s.padding ?? "md"]} ${boxed}"${styleAttr}>${inner || ""}</div>`;
    }
    case "custom": {
      const cfg = block.config ?? {};
      switch (block.custom) {
        case "form":
          return formEmbed(pageId ?? "", block.id, cfg);
        case "map":
          return mapEmbed(cfg);
        case "youtube":
          return youtubeEmbed(String(cfg.url ?? ""));
        case "instagram":
          return instagramEmbed(String(cfg.url ?? ""));
        case "embed": {
          const src = String(cfg.src ?? "");
          return /^https:\/\//.test(src)
            ? `<div class="cms-embed"><iframe src="${esc(src)}" title="${esc(cfg.title ?? "Embedded content")}" frameborder="0" allowfullscreen loading="lazy"></iframe></div>`
            : `<p class="cms-block-error">Embed requires an https:// URL.</p>`;
        }
        default:
          return `<div class="cms-text"><p>${esc(cfg.note ?? cfg.content ?? "AI-built block")}</p></div>`;
      }
    }
    default:
      return "";
  }
}

// ----------------------------------------------------------------------------
// Sitewide theming: recommended presets + shared base styles. The preset CSS
// is tiny and scoped to .cms-* so any custom stylesheet can layer on top.
// ----------------------------------------------------------------------------

/** Recommended global stylesheet presets (selected in Site Settings). */
export const THEME_PRESETS: Record<string, { label: string; css: string }> = {
  clean: {
    label: "Clean & Minimal",
    css: `
.cms-shell{max-width:960px;margin:0 auto;padding:40px 20px;line-height:1.7}
.cms-site-header{border-bottom:1px solid #eee;padding:16px 20px}
.cms-site-header .cms-site-name{font-size:1.4rem;font-weight:700;letter-spacing:-.02em}
.cms-site-footer{border-top:1px solid #eee;margin-top:40px;padding:24px 20px;color:#666;font-size:.9rem}
.cms-text h2{margin-top:2rem}
.cms-block{margin:1.5rem 0}
`,
  },
  dark: {
    label: "Dark & Sleek",
    css: `
.cms-site-header,.cms-shell{background:#0f1115;color:#e7e9ee}
.cms-shell{max-width:960px;margin:0 auto;padding:40px 20px;line-height:1.7}
.cms-site-header{border-bottom:1px solid #262a33;padding:16px 20px;background:#0f1115;color:#e7e9ee}
.cms-site-header .cms-site-name{font-size:1.4rem;font-weight:700;letter-spacing:-.02em}
.cms-site-footer{border-top:1px solid #262a33;margin-top:40px;padding:24px 20px;color:#8b93a3;font-size:.9rem;background:#0f1115}
.cms-text h2{margin-top:2rem}
.cms-text a{color:#7db4ff}
.cms-block{margin:1.5rem 0}
.cms-section{background:#171a21;border:1px solid #262a33}
.cms-image figcaption{color:#8b93a3}
`,
  },
  corporate: {
    label: "Corporate",
    css: `
.cms-shell{max-width:1100px;margin:0 auto;padding:48px 24px;line-height:1.65;color:#1f2937}
.cms-site-header{border-bottom:2px solid #1d4ed8;padding:18px 24px;background:#fff}
.cms-site-header .cms-site-name{font-size:1.5rem;font-weight:700;color:#1d4ed8;letter-spacing:-.01em}
.cms-site-header .cms-site-tagline{color:#6b7280;font-size:.95rem}
.cms-site-footer{border-top:2px solid #e5e7eb;margin-top:48px;padding:28px 24px;color:#6b7280;font-size:.9rem;background:#f9fafb}
.cms-text h1{font-size:2.25rem;color:#111827}
.cms-text h2{font-size:1.6rem;color:#111827;margin-top:2.2rem}
.cms-text a{color:#1d4ed8;text-decoration:underline}
.cms-block{margin:1.75rem 0}
.cms-btn{background:#1d4ed8}
`,
  },
  bold: {
    label: "Bold & Creative",
    css: `
.cms-shell{max-width:960px;margin:0 auto;padding:48px 20px;line-height:1.7}
.cms-site-header{background:linear-gradient(135deg,#7c3aed,#db2777);color:#fff;padding:20px 24px}
.cms-site-header .cms-site-name{font-size:1.5rem;font-weight:800;letter-spacing:-.02em}
.cms-site-header .cms-site-tagline{opacity:.85;font-size:.95rem}
.cms-site-footer{margin-top:48px;padding:24px 20px;color:#6b7280;font-size:.9rem;border-top:4px solid #7c3aed}
.cms-text h1{font-size:2.5rem;font-weight:800;letter-spacing:-.03em}
.cms-text h2{font-size:1.8rem;font-weight:700;letter-spacing:-.02em;margin-top:2.2rem}
.cms-text a{color:#7c3aed;font-weight:600}
.cms-block{margin:1.5rem 0}
.cms-section{background:linear-gradient(180deg,#faf5ff,#fff)}
.cms-btn{background:linear-gradient(135deg,#7c3aed,#db2777);font-weight:700}
`,
  },
};

export const CMS_HEADER_FOOTER_STYLES = `
.cms-site-header{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}
.cms-site-name{font-weight:700}
.cms-site-tagline{font-size:.9rem;opacity:.8}
.cms-site-nav{display:flex;gap:18px;list-style:none;margin:0;padding:0;flex-wrap:wrap;align-items:center}
.cms-site-nav a{text-decoration:none;font-size:.95rem;font-weight:500}
.cms-site-nav a:hover{text-decoration:underline}
.cms-nav-links{display:flex;gap:16px;list-style:none;margin:0;padding:0}
.cms-nav-links a{text-decoration:none;font-size:.95rem}
.cms-archive{list-style:none;margin:0;padding:0}
.cms-archive li{border-bottom:1px solid #eee;padding:14px 0}
.cms-archive a{display:flex;align-items:center;justify-content:space-between;gap:12px;text-decoration:none}
.cms-archive-title{font-weight:600;font-size:1.05rem}
.cms-archive-cat{font-size:.8rem;color:#666;background:#f3f4f6;padding:2px 8px;border-radius:99px}
`;

/** Shared minimal CSS for rendered pages (kept here so preview + public match). */
export const CMS_STYLES = `
.cms-shell{font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;max-width:960px;margin:0 auto;padding:32px 20px;line-height:1.6;color:#1a1a1a}
.cms-text h1{font-size:2rem;margin:1rem 0 .5rem}.cms-text h2{font-size:1.5rem;margin:1.2rem 0 .4rem}.cms-text h3{font-size:1.2rem;margin:1rem 0 .3rem}
.cms-text p{margin:.5rem 0}.cms-text a{color:#2563eb}.cms-text img{max-width:100%;border-radius:8px}
.cms-image{margin:1.2rem 0}.cms-image img{max-width:100%;border-radius:10px}.cms-image figcaption{font-size:.85rem;color:#666;margin-top:.4rem}
/* Blog images: hero first, then alternating left/right floats so text wraps
   around them and they are never stacked. Unfloat on small screens. */
.cms-blog-img{margin:1.2rem 0}
.cms-hero-img img{display:block;width:100%;max-width:720px;margin:0 auto;border-radius:12px}
.cms-float-left{float:left;width:44%;margin:.3rem 1.4rem .8rem 0}
.cms-float-right{float:right;width:44%;margin:.3rem 0 .8rem 1.4rem}
.cms-float-left img,.cms-float-right img{width:100%;border-radius:10px}
.cms-text h1,.cms-text h2,.cms-text h3{clear:both}
.cms-embed{position:relative;width:100%;padding-top:56.25%;margin:1.2rem 0}.cms-embed iframe{position:absolute;inset:0;width:100%;height:100%;border:0;border-radius:10px}
.cms-embed.cms-map{padding-top:60%}
.cms-form{display:grid;gap:.9rem;max-width:520px;margin:1.2rem auto;padding:1.5rem;border:1px solid #e5e7eb;border-radius:12px;background:#fafafa}
.cms-field{display:grid;gap:.3rem;font-size:.9rem}.cms-field span{font-weight:600;text-transform:capitalize}
.cms-field input,.cms-field textarea{padding:.6rem .7rem;border:1px solid #d1d5db;border-radius:8px;font:inherit}
.cms-btn{padding:.65rem 1.2rem;border:0;border-radius:8px;background:#2563eb;color:#fff;font-weight:600;cursor:pointer}
.cms-form-status{margin:0;font-size:.9rem}.cms-form-status.ok{color:#16a34a}.cms-form-status.err{color:#dc2626}
.cms-block-error{color:#dc2626;font-size:.9rem;border:1px dashed #fca5a5;padding:.6rem;border-radius:8px}
.cms-block{margin:1rem 0;border-radius:10px}
.cms-pad-sm{padding:.6rem}.cms-pad-md{padding:1.2rem}.cms-pad-lg{padding:2rem}
.cms-align-left{text-align:left}.cms-align-center{text-align:center}.cms-align-right{text-align:right}
.cms-w-wide{width:75%}.cms-w-half{width:50%}.cms-w-third{width:33.33%}
.cms-section{margin:1.5rem 0;border-radius:12px;overflow:hidden}.cms-section-inner{max-width:960px;margin:0 auto;position:relative;z-index:1}
.cms-section-bg{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;z-index:0;opacity:.9}
.cms-section-bleed{border-radius:0;margin-left:calc(50% - 50vw);margin-right:calc(50% - 50vw);width:auto}
.cms-columns{display:grid;gap:1.4rem;margin:1.5rem 0}
.cms-columns-2{grid-template-columns:repeat(2,1fr)}
.cms-columns-3{grid-template-columns:repeat(3,1fr)}
.cms-columns-4{grid-template-columns:repeat(4,1fr)}
@media(max-width:720px){.cms-columns-2,.cms-columns-3,.cms-columns-4{grid-template-columns:1fr}}
@media(max-width:640px){.cms-w-wide,.cms-w-half,.cms-w-third{width:100%}.cms-float-left,.cms-float-right{float:none;width:100%;margin:.8rem 0}}
`;
