/**
 * Content Map batch runner — server-side, durable, page-independent.
 *
 * The old design ran the batch as a client-side `for` loop: navigating away
 * from the map page unmounted the component and silently killed the queue.
 * This module owns the loop on the SERVER instead:
 *
 *   - The UI POSTs /api/content-map/batch { action: "start" } and gets an
 *     immediate ack; the loop keeps running in this Node process regardless
 *     of what the browser does.
 *   - Row statuses are persisted (planned → generating → done/failed), so
 *     any page (or a fresh tab) shows the truth; the UI just polls.
 *   - "Stop after this one" sets a flag; the in-flight item finishes, the
 *     rest of the claimed queue returns to planned.
 *   - If the process restarts mid-batch, stale `generating` rows are healed
 *     back to `planned` on the next start (or status read).
 *
 * Each item is generated by calling the project's own /api/generate-content
 * endpoint over loopback with the STARTING USER's cookie header — every auth,
 * billing, rate-limit, gate, scoring, and persistence behavior of the normal
 * path applies unchanged. A failed item is recorded and the queue continues;
 * one bad row never kills the batch.
 *
 * NOTE: this is in-process durability (right for this deployment: a
 * long-lived Node server). A serverless deployment would move the loop into
 * an Inngest function instead — the seam (start/status/stop + persisted row
 * states) is already shaped for that.
 */

import { createClient } from "@supabase/supabase-js";
import { isPlaceholderTitle } from "@/lib/content-map-import";

/** One workspace's live runner. Keyed tenant:workspace. */
interface RunnerState {
  tenantId: string;
  workspaceId: string | null;
  /** Cookie header captured from the starting request (auth for self-calls). */
  cookie: string;
  /** Loopback origin of this server (from the starting request). */
  origin: string;
  clientId: string | null;
  brandVoice: string | null;
  imagePref: number | "auto";
  /** Remaining item ids, in order. */
  queue: string[];
  total: number;
  done: number;
  running: boolean;
  stopRequested: boolean;
}

const runners = new Map<string, RunnerState>();

function runnerKey(tenantId: string, workspaceId: string | null): string {
  return `${tenantId}:${workspaceId ?? "-"}`;
}

function serviceSupabase() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { autoRefreshToken: false, persistSession: false } }
  );
}

/**
 * Heal rows stuck in `generating` (a previous process died mid-batch) back to
 * planned. Called when a batch starts; cheap and idempotent.
 */
async function resetStaleGenerating(tenantId: string, workspaceId: string | null) {
  const supabase = serviceSupabase();
  let query = supabase
    .from("content_map_items")
    .update({ status: "planned", error: null, updated_at: new Date().toISOString() })
    .eq("tenant_id", tenantId)
    .eq("status", "generating");
  query = workspaceId ? query.eq("workspace_id", workspaceId) : query.is("workspace_id", null);
  await query;
}

export interface StartBatchArgs {
  tenantId: string;
  workspaceId: string | null;
  cookie: string;
  origin: string;
  clientId: string | null;
  brandVoice: string | null;
  imagePref: number | "auto";
  /**
   * Restrict the run to these item ids (per-row "Generate" buttons). When
   * omitted, every planned item in the workspace is claimed.
   */
  itemIds?: string[];
}

export interface StartBatchResult {
  started: boolean;
  reason?: "already_running" | "nothing_planned";
  claimed?: number;
}

/**
 * Claim every planned item for the workspace and start the server-side loop.
 * Returns immediately; the loop continues without any browser attached.
 */
export async function startBatch(args: StartBatchArgs): Promise<StartBatchResult> {
  const key = runnerKey(args.tenantId, args.workspaceId);
  const existing = runners.get(key);
  if (existing?.running) {
    return { started: false, reason: "already_running" };
  }

  await resetStaleGenerating(args.tenantId, args.workspaceId);

  const supabase = serviceSupabase();
  let plannedQuery = supabase
    .from("content_map_items")
    .select("id")
    .eq("tenant_id", args.tenantId)
    // Explicit per-row retries may re-run FAILED rows ("re-run the row to
    // link it"); full-map runs still only pick up planned rows.
    .in(
      "status",
      args.itemIds && args.itemIds.length > 0
        ? ["planned", "failed"]
        : ["planned"]
    )
    .order("created_at", { ascending: true });
  plannedQuery = args.workspaceId
    ? plannedQuery.eq("workspace_id", args.workspaceId)
    : plannedQuery.is("workspace_id", null);
  if (args.clientId) plannedQuery = plannedQuery.eq("client_id", args.clientId);
  if (args.itemIds && args.itemIds.length > 0) {
    plannedQuery = plannedQuery.in("id", args.itemIds);
  }
  const { data: plannedRows, error } = await plannedQuery;
  if (error) throw new Error(error.message);
  const ids = (plannedRows ?? []).map((r) => r.id as string);
  if (ids.length === 0) {
    return { started: false, reason: "nothing_planned" };
  }

  // Claim them: planned → generating, persisted so any viewer sees the truth.
  const { error: claimErr } = await supabase
    .from("content_map_items")
    .update({ status: "generating", error: null, updated_at: new Date().toISOString() })
    .in("id", ids);
  if (claimErr) throw new Error(claimErr.message);

  const state: RunnerState = {
    tenantId: args.tenantId,
    workspaceId: args.workspaceId,
    cookie: args.cookie,
    origin: args.origin.replace(/\/$/, ""),
    clientId: args.clientId,
    brandVoice: args.brandVoice,
    imagePref: args.imagePref,
    queue: [...ids],
    total: ids.length,
    done: 0,
    running: true,
    stopRequested: false,
  };
  runners.set(key, state);

  // Fire-and-forget: the HTTP response returns now; the loop keeps going.
  void runLoop(state, key).catch((err) => {
    console.error("[content-map-batch] Loop crashed:", err);
  });

  return { started: true, claimed: ids.length };
}

/**
 * Placeholder fill at generation time: a row whose title is a content
 * CATEGORY ("Blog Promotion", "Local Attraction", "GBP Post"…) gets a real
 * topic invented by the model before generating — grounded in the client's
 * business, its website, and the season around the row's planned publish
 * date. The expanded topic replaces the row's stored one for the generation
 * call only (the map row keeps its original title; the generated post shows
 * the real topic). Never throws — on any failure the row generates from its
 * original title/topic as before.
 */
async function expandPlaceholderTopic(
  state: RunnerState,
  item: { title: string | null; topic: string | null; scheduled_at: string | null; client_id: string | null }
): Promise<string | null> {
  const category = (item.title ?? item.topic ?? "").trim();
  if (!category || !isPlaceholderTitle(category)) return null;
  try {
    const supabase = serviceSupabase();

    // Grounding: the client's business + website.
    let clientContext = "";
    if (item.client_id) {
      const { data: client } = await supabase
        .from("clients")
        .select("name, website")
        .eq("id", item.client_id)
        .eq("tenant_id", state.tenantId)
        .maybeSingle();
      if (client?.name) {
        clientContext += `Client: ${client.name}`;
        if (client.website) clientContext += ` (website: ${client.website})`;
        clientContext += "\n";
      }
    }
    // Season/date context: the planned publish month drives seasonal angles.
    const when = item.scheduled_at ? new Date(item.scheduled_at) : new Date();
    const month = when.toLocaleString("en-US", { month: "long", year: "numeric" });
    const season =
      ["dec", "jan", "feb"].includes(when.toISOString().slice(5, 7).toLowerCase().slice(0, 3))
        ? "winter"
        : ["mar", "apr", "may"].includes(when.toISOString().slice(5, 7).toLowerCase().slice(0, 3))
          ? "spring"
          : ["jun", "jul", "aug"].includes(when.toISOString().slice(5, 7).toLowerCase().slice(0, 3))
            ? "summer"
            : "autumn";

    const { generateText } = await import("@/lib/ai/orchestrator");
    const topic = await generateText(
      "team_chat" as never,
      `A content calendar has a slot whose type is "${category}" (a content CATEGORY, not a topic). Invent the specific, concrete blog topic this slot should be.

${clientContext}
Publish slot: ${month} (${season})

Rules:
- The topic must be a specific, publishable article idea that a real reader would search for.
- Ground it in this client's actual business and the season/month of the slot.
- 8-14 words. No category words like "promotion" or "update" in the topic itself.
- Return ONLY the topic text — no quotes, no explanation.`,
      state.tenantId,
      { temperature: 0.8, maxTokens: 80 }
    );
    const cleaned = topic.trim().replace(/^["']+|["']+$/g, "").slice(0, 200);
    if (cleaned.length < 8) return null;
    console.log(
      `[content-map-batch] Expanded placeholder "${category}" → "${cleaned}"`
    );
    return cleaned;
  } catch (err) {
    console.warn("[content-map-batch] Placeholder expansion failed:", err);
    return null;
  }
}

/**
 * A lost generation response (network hiccup on the loopback call) does NOT
 * mean the generation failed — the post may already be committed. Before
 * declaring a row failed, reconcile against the DB: link the post that was
 * actually created instead of letting a retry duplicate it.
 */
async function reconcileCommittedPost(
  supabase: ReturnType<typeof serviceSupabase>,
  tenantId: string,
  item: { title: string | null; topic: string | null; content_type: string },
  itemId: string
): Promise<string | null> {
  // Only posts from the last day can be this item's result (titles/topics
  // repeat across campaigns; recency keeps the match unambiguous).
  const since = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
  const base = () =>
    supabase
      .from("posts")
      .select("id")
      .eq("tenant_id", tenantId)
      .eq("ai_generated", true)
      .gte("created_at", since)
      .order("created_at", { ascending: false })
      .limit(1);
  // Primary: the map row's title (blog) or topic (social). Fallback: the
  // row's topic — the model may rephrase the title, but the topic is what
  // generation was seeded from. The fallback only runs on the more recent
  // post, so an unrelated generation that happened minutes earlier can't be
  // mis-linked by a shared topic.
  const match = item.content_type === "social" ? "topic" : "title";
  const primary =
    match === "topic"
      ? await base().eq("content->>topic", item.topic ?? "")
      : await base().eq("content->>title", item.title ?? "");
  if (primary.data?.[0]?.id) return primary.data[0].id;
  if (item.topic) {
    const fallback = await base().eq("content->>topic", item.topic);
    return fallback.data?.[0]?.id ?? null;
  }
  return null;
}

/** Generate ONE item through the normal endpoint, then record the outcome. */
async function generateOne(state: RunnerState, itemId: string): Promise<void> {
  const supabase = serviceSupabase();
  const now = () => new Date().toISOString();

  // Fresh row read (the UI may have edited fields after claim).
  let itemQuery = supabase
    .from("content_map_items")
    .select(
      "id, title, topic, keywords, content_type, platforms, external_links, scheduled_at, auto_publish, client_id"
    )
    .eq("tenant_id", state.tenantId)
    .eq("id", itemId);
  itemQuery = state.workspaceId
    ? itemQuery.eq("workspace_id", state.workspaceId)
    : itemQuery.is("workspace_id", null);
  const { data: item } = await itemQuery.maybeSingle();
  if (!item) {
    // Deleted (or moved workspace) mid-queue — skip without failing.
    return;
  }

  // Placeholder rows (category-style titles with no real topic) get a real
  // topic invented from the client's business + the season before generating.
  // The expanded topic is persisted on the row: the UI shows what will/was
  // generated, and reconcile-by-topic still matches after a lost response.
  const expandedTopic = await expandPlaceholderTopic(state, item);
  const effectiveTopic = expandedTopic ?? item.topic ?? item.title ?? "";
  if (expandedTopic) {
    await serviceSupabase()
      .from("content_map_items")
      .update({ topic: expandedTopic, updated_at: new Date().toISOString() })
      .eq("tenant_id", state.tenantId)
      .eq("id", itemId);
  }

  try {
    const res = await fetch(`${state.origin}/api/generate-content`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Cookie: state.cookie,
        // Fresh connection per call: reused keep-alive sockets race the dev
        // server's idle close and can abort a large response mid-body
        // ("fetch failed") even though the generation succeeded.
        Connection: "close",
      },
      body: JSON.stringify({
        title: item.title,
        topic: effectiveTopic || undefined,
        keywords: (item.keywords ?? []).length > 0 ? item.keywords : undefined,
        brandVoice: state.brandVoice ?? undefined,
        clientId: state.clientId ?? undefined,
        platforms: item.content_type === "social" ? item.platforms ?? [] : [],
        externalLinks: (item.external_links ?? []).length > 0 ? item.external_links : undefined,
        socialOnly: item.content_type === "social",
        imageAuto: state.imagePref === "auto" || undefined,
        imageCount: state.imagePref === "auto" ? undefined : state.imagePref,
        // The CSV's / row's suggested publish time — stored on the draft as a
        // suggestion (status stays `draft`; the approval flow still governs).
        scheduledAt: item.scheduled_at ?? undefined,
        // Row-level automation (migrations 104+105): any row (blog or social)
        // with auto_publish='wordpress' AND a planned date gets the 15-minute
        // hold armed on its gate-cleared drafts. The hold processor schedules
        // blogs to WordPress and queues social posts to the publish cron.
        autoPublish:
          item.auto_publish === "wordpress" && item.scheduled_at
            ? "wordpress"
            : undefined,
      }),
    });
    const json = (await res.json().catch(() => ({}))) as Record<string, unknown>;

    if (!res.ok) {
      await supabase
        .from("content_map_items")
        .update({
          status: "failed",
          error: (json.error as string) ?? `Generation failed (${res.status})`,
          gate: (json.gate as Record<string, unknown>) ?? null,
          updated_at: now(),
        })
        .eq("tenant_id", state.tenantId)
        .eq("id", itemId);
      return;
    }

    // Social-only rows: the platform posts themselves are the output; link
    // the first one. Blog rows: the blog post id.
    let postId: string | undefined;
    let gate: unknown = null;
    if (json.socialOnly) {
      const posts = (json.socialPosts ?? []) as { id?: string }[];
      postId = posts[0]?.id;
    } else {
      const bp = json.blogPost as { id?: string; gate?: unknown } | undefined;
      postId = bp?.id;
      gate = bp?.gate ?? null;
    }
    if (!postId) {
      await supabase
        .from("content_map_items")
        .update({ status: "failed", error: "Generation returned no post id", updated_at: now() })
        .eq("tenant_id", state.tenantId)
        .eq("id", itemId);
      return;
    }

    await supabase
      .from("content_map_items")
      .update({
        status: "done",
        linked_post_id: postId,
        gate: gate as Record<string, unknown> | null,
        error: null,
        updated_at: now(),
      })
      .eq("tenant_id", state.tenantId)
      .eq("id", itemId);
  } catch (err) {
    // Network-level failure of the self-call — but the generation may still
    // COMMIT a moment later (the server keeps working; only the response was
    // lost). Reconcile now, then once more after a grace period, because the
    // post row lands only when the whole pipeline finishes (~30-100s).
    const reconcileArgs = {
      title: item.title,
      topic: item.topic,
      content_type: item.content_type ?? "blog",
    } as const;
    try {
      const existingPostId = await reconcileCommittedPost(
        supabase,
        state.tenantId,
        reconcileArgs,
        itemId
      );
      if (existingPostId) {
        await supabase
          .from("content_map_items")
          .update({
            status: "done",
            linked_post_id: existingPostId,
            error: null,
            updated_at: now(),
          })
          .eq("tenant_id", state.tenantId)
          .eq("id", itemId);
        return;
      }
    } catch {
      // reconciliation is best-effort
    }
    // Grace-period retry — NON-blocking so the queue never stalls: the row
    // reads "failed" now, but a detached check runs after 90s (a typical
    // gated generation's length) and flips the row to done when the post
    // landed after the response was lost.
    void (async () => {
      await new Promise((r) => setTimeout(r, 90_000));
      try {
        const latePostId = await reconcileCommittedPost(
          serviceSupabase(),
          state.tenantId,
          reconcileArgs,
          itemId
        );
        if (latePostId) {
          await serviceSupabase()
            .from("content_map_items")
            .update({
              status: "done",
              linked_post_id: latePostId,
              error: null,
              updated_at: new Date().toISOString(),
            })
            .eq("tenant_id", state.tenantId)
            .eq("id", itemId);
        }
      } catch {
        // still best-effort
      }
    })();
    await supabase
      .from("content_map_items")
      .update({
        status: "failed",
        error:
          err instanceof Error
            ? `${err.message} — the post may still appear; re-run the row to link it instead of regenerating`
            : "Generation failed",
        updated_at: now(),
      })
      .eq("tenant_id", state.tenantId)
      .eq("id", itemId)
      .then(undefined, () => undefined); // recording must never throw
  }
}

/** The durable loop: one item at a time, sequential, stop-flag aware. */
async function runLoop(state: RunnerState, key: string): Promise<void> {
  try {
    while (state.queue.length > 0 && !state.stopRequested) {
      const itemId = state.queue[0];
      await generateOne(state, itemId);
      state.queue.shift();
      state.done += 1;
    }
    // Stopped with items still claimed → return them to planned.
    if (state.queue.length > 0) {
      const supabase = serviceSupabase();
      await supabase
        .from("content_map_items")
        .update({ status: "planned", error: null, updated_at: new Date().toISOString() })
        .in("id", state.queue);
    }
  } finally {
    state.running = false;
    runners.delete(key);
  }
}

/** "Stop after this one": the in-flight item finishes, the queue halts. */
export function stopBatch(tenantId: string, workspaceId: string | null): boolean {
  const state = runners.get(runnerKey(tenantId, workspaceId));
  if (!state?.running) return false;
  state.stopRequested = true;
  return true;
}

export interface BatchStatus {
  running: boolean;
  done: number;
  total: number;
}

export function getBatchStatus(tenantId: string, workspaceId: string | null): BatchStatus {
  const state = runners.get(runnerKey(tenantId, workspaceId));
  if (!state?.running) return { running: false, done: 0, total: 0 };
  return { running: true, done: state.done, total: state.total };
}

