// ============================================================================
// Landing page content model
//
// The public marketing page (/ ) reads from site_settings.landing_content,
// falling back to the compiled defaults below whenever a field is missing or
// the column is null. The super admin edits all of this in the visual page
// builder at /dashboard/admin/page-builder.
// ============================================================================

export interface LandingLogo {
  name: string;
  url: string;
  href?: string;
}

export interface LandingFeature {
  title: string;
  description: string;
}

export interface LandingStep {
  step: string;
  title: string;
  description: string;
}

export interface LandingTestimonial {
  quote: string;
  author: string;
}

export interface LandingFaq {
  q: string;
  a: string;
}

/** A pricing tier. `planId` is the Stripe sync key (product metadata
 * `plan_id`) — it must stay in sync with Stripe, so the builder renders it
 * read-only. Everything else is editable display copy. */
export interface LandingPlan {
  planId: string;
  name: string;
  price: string;
  description: string;
  features: string[];
  popular?: boolean;
}

/** An a-la-carte hub add-on. `hubId` is the Stripe sync key (product metadata
 * `hub_id`) — read-only in the builder. */
export interface LandingHub {
  hubId: string;
  name: string;
  price: string;
  blurb: string;
}

/** A standalone marketing page (rendered at /p/<slug>). */
export interface LandingPage {
  slug: string;
  title: string;
  body: string;
}

/** A custom link shown in the landing page header navigation. */
export interface LandingNavLink {
  label: string;
  href: string;
}

export interface LandingContent {
  heroTitle: string;
  heroSubtitle: string;
  heroBadge: string;
  featuresHeading: string;
  featuresSubheading: string;
  features: LandingFeature[];
  howItWorksHeading: string;
  howItWorksSubheading: string;
  howItWorks: LandingStep[];
  logoStripHeading: string;
  logos: LandingLogo[];
  testimonialsHeading: string;
  testimonials: LandingTestimonial[];
  faqHeading: string;
  faqs: LandingFaq[];
  pricingHeading: string;
  pricingSubheading: string;
  plans: LandingPlan[];
  hubsHeading: string;
  hubsSubheading: string;
  hubs: LandingHub[];
  ctaTitle: string;
  ctaSubtitle: string;
  ctaButton: string;
  pages: LandingPage[];
  navLinks: LandingNavLink[];
}

/** The compiled-in defaults the landing page ships with. */
export const DEFAULT_LANDING_CONTENT: LandingContent = {
  heroTitle: "The All-in-One Platform for Digital Agencies",
  heroSubtitle:
    "AI-powered content creation, white-label client portals, SEO campaign proposals, social media scheduling, and billing — all in one platform.",
  heroBadge: "14-day free trial · No credit card required · Cancel anytime",
  featuresHeading: "Everything You Need to Run Your Agency",
  featuresSubheading:
    "One platform that replaces 6+ tools. Save time, reduce costs, and deliver better results for your clients.",
  features: [
    {
      title: "AI Content Generation",
      description:
        "Blog posts, social captions, and SEO proposals generated by AI using your own API keys.",
    },
    {
      title: "White-Label Portals",
      description:
        "Each client gets their own branded portal to review and approve content.",
    },
    {
      title: "Content Calendar",
      description:
        "Schedule and manage all your content across platforms in one view.",
    },
    {
      title: "Multi-Tenant Security",
      description:
        "Each agency is fully isolated. Your data, your keys, your clients.",
    },
    {
      title: "Automated Publishing",
      description:
        "Connect social accounts and blog platforms — publish directly from the platform.",
    },
    {
      title: "Team Collaboration",
      description:
        "Agency admins, editors, and clients all have role-based access.",
    },
  ],
  howItWorksHeading: "How it works",
  howItWorksSubheading: "From signup to your first published post in three steps.",
  howItWorks: [
    {
      step: "01",
      title: "Add your API key",
      description:
        "Bring your own OpenAI, DeepSeek, or other API key. Your data stays yours and your AI spend is predictable.",
    },
    {
      step: "02",
      title: "Create a workspace",
      description:
        "Set up a workspace per client with brand voice, knowledge base, and publishing connections.",
    },
    {
      step: "03",
      title: "Generate & publish",
      description:
        "Generate blog posts, social captions, and SEO proposals — then schedule and publish from one calendar.",
    },
  ],
  logoStripHeading: "Trusted by growing agencies",
  logos: [],
  testimonialsHeading: "What agencies are saying",
  testimonials: [],
  faqHeading: "Frequently asked questions",
  faqs: [
    {
      q: "Do I need my own AI API key?",
      a: "Content generation uses your own OpenAI, DeepSeek, or compatible API keys so you control cost and data. The SEO audit tool runs on our platform and needs no key.",
    },
    {
      q: "Is my client data isolated?",
      a: "Yes. Every agency is a fully isolated tenant. Your clients, content, and API keys are never shared with other tenants.",
    },
    {
      q: "What does the 14-day free trial include?",
      a: "Full access to every feature on your chosen plan. No credit card required. Upgrade or cancel anytime.",
    },
    {
      q: "Can I white-label the portal for my clients?",
      a: "Yes. Each client gets a branded portal to review and approve content — no Agency OS branding required.",
    },
  ],
  pricingHeading: "Simple, Transparent Pricing",
  pricingSubheading:
    "Start with a 14-day free trial. No credit card required. Upgrade anytime.",
  plans: [
    {
      planId: "foundation",
      name: "Foundation",
      price: "49",
      description: "Everything on the platform, at starter levels.",
      features: [
        "All six hubs included",
        "4 blogs / 40 socials per month",
        "40 images, 8 videos per month",
        "200K AI tokens / month",
        "Content calendar + approvals",
        "White-label portal",
        "Email support",
      ],
    },
    {
      planId: "growth",
      name: "Growth",
      price: "99",
      description: "For growing agencies with multiple clients.",
      features: [
        "All six hubs included",
        "12 blogs / 150 socials per month",
        "150 images, 30 videos per month",
        "750K AI tokens / month",
        "SEO campaign automation",
        "Competitor analysis",
        "Priority support",
      ],
      popular: true,
    },
    {
      planId: "dominance",
      name: "Dominance",
      price: "299",
      description: "Full-scale content engine, white-label ready.",
      features: [
        "All six hubs included",
        "40 blogs / 500 socials per month",
        "500 images, 120 videos per month",
        "2.5M AI tokens / month",
        "Outreach + link building",
        "Dedicated account manager",
        "Custom integrations",
      ],
    },
  ],
  hubsHeading: "Or pick just the hub you need",
  hubsSubheading:
    "A-la-carte add-ons — stack a few, or take an all-in-one tier above. Any 3 hubs for $69/mo.",
  hubs: [
    { hubId: "content", name: "Content Hub", price: "29", blurb: "Blogs, SEO scoring, content calendar + publish" },
    { hubId: "social", name: "Social Hub", price: "29", blurb: "Captions, scheduling, approvals, 3 profiles" },
    { hubId: "video", name: "Video Hub", price: "29", blurb: "Text-to-video & image-to-video generation" },
    { hubId: "website", name: "Website Hub", price: "29", blurb: "Web Builder — build and host client sites" },
    { hubId: "outreach", name: "Outreach Hub", price: "29", blurb: "Guest posts, reply watching, opportunities" },
    { hubId: "ai_team", name: "AI Team", price: "49", blurb: "The full employee roster, chat + campaigns" },
  ],
  ctaTitle: "Ready to Scale Your Agency?",
  ctaSubtitle:
    "Replace your content tool stack with one platform. Start your 14-day free trial today.",
  ctaButton: "Get Started Free",
  pages: [],
  navLinks: [],
};

// ---------------------------------------------------------------------------
// Sanitization — never trust DB content when rendering the public page.
// ---------------------------------------------------------------------------

function asString(value: unknown, fallback: string): string {
  return typeof value === "string" && value.trim().length > 0
    ? value.trim()
    : fallback;
}

function asStringArray(value: unknown): string[] | null {
  if (!Array.isArray(value)) return null;
  const out: string[] = [];
  for (const v of value) {
    if (typeof v === "string" && v.trim()) out.push(v.trim());
  }
  return out.length ? out : null;
}

function asFeatures(value: unknown): LandingFeature[] | null {
  if (!Array.isArray(value)) return null;
  const out: LandingFeature[] = [];
  for (const v of value) {
    if (!v || typeof v !== "object") continue;
    const item = v as Record<string, unknown>;
    const title = typeof item.title === "string" ? item.title.trim() : "";
    const description =
      typeof item.description === "string" ? item.description.trim() : "";
    if (title) out.push({ title, description });
  }
  return out.length ? out : null;
}

function asSteps(value: unknown): LandingStep[] | null {
  if (!Array.isArray(value)) return null;
  const out: LandingStep[] = [];
  for (const v of value) {
    if (!v || typeof v !== "object") continue;
    const item = v as Record<string, unknown>;
    const title = typeof item.title === "string" ? item.title.trim() : "";
    if (!title) continue;
    out.push({
      step: typeof item.step === "string" ? item.step.trim() : "",
      title,
      description:
        typeof item.description === "string" ? item.description.trim() : "",
    });
  }
  return out.length ? out : null;
}

function asLogos(value: unknown): LandingLogo[] | null {
  if (!Array.isArray(value)) return null;
  const out: LandingLogo[] = [];
  for (const v of value) {
    if (!v || typeof v !== "object") continue;
    const item = v as Record<string, unknown>;
    const name = typeof item.name === "string" ? item.name.trim() : "";
    const url = typeof item.url === "string" ? item.url.trim() : "";
    if (!url) continue;
    out.push({
      name: name || url,
      url,
      href: typeof item.href === "string" ? item.href.trim() : undefined,
    });
  }
  return out.length ? out : null;
}

function asTestimonials(value: unknown): LandingTestimonial[] | null {
  if (!Array.isArray(value)) return null;
  const out: LandingTestimonial[] = [];
  for (const v of value) {
    if (!v || typeof v !== "object") continue;
    const item = v as Record<string, unknown>;
    const quote = typeof item.quote === "string" ? item.quote.trim() : "";
    if (!quote) continue;
    out.push({
      quote,
      author: typeof item.author === "string" ? item.author.trim() : "",
    });
  }
  return out.length ? out : null;
}

function asPlans(value: unknown): LandingPlan[] | null {
  if (!Array.isArray(value)) return null;
  const out: LandingPlan[] = [];
  for (const v of value) {
    if (!v || typeof v !== "object") continue;
    const item = v as Record<string, unknown>;
    const planId = typeof item.planId === "string" ? item.planId.trim() : "";
    const name = typeof item.name === "string" ? item.name.trim() : "";
    if (!planId || !name) continue;
    out.push({
      planId,
      name,
      price: typeof item.price === "string" ? item.price.trim() : "",
      description:
        typeof item.description === "string" ? item.description.trim() : "",
      features: asStringArray(item.features) ?? [],
      popular: item.popular === true,
    });
  }
  return out.length ? out : null;
}

function asHubs(value: unknown): LandingHub[] | null {
  if (!Array.isArray(value)) return null;
  const out: LandingHub[] = [];
  for (const v of value) {
    if (!v || typeof v !== "object") continue;
    const item = v as Record<string, unknown>;
    const hubId = typeof item.hubId === "string" ? item.hubId.trim() : "";
    const name = typeof item.name === "string" ? item.name.trim() : "";
    if (!hubId || !name) continue;
    out.push({
      hubId,
      name,
      price: typeof item.price === "string" ? item.price.trim() : "",
      blurb: typeof item.blurb === "string" ? item.blurb.trim() : "",
    });
  }
  return out.length ? out : null;
}

function asFaqs(value: unknown): LandingFaq[] | null {
  if (!Array.isArray(value)) return null;
  const out: LandingFaq[] = [];
  for (const v of value) {
    if (!v || typeof v !== "object") continue;
    const item = v as Record<string, unknown>;
    const q = typeof item.q === "string" ? item.q.trim() : "";
    if (!q) continue;
    out.push({ q, a: typeof item.a === "string" ? item.a.trim() : "" });
  }
  return out.length ? out : null;
}

function asPages(value: unknown): LandingPage[] | null {
  if (!Array.isArray(value)) return null;
  const out: LandingPage[] = [];
  const seen = new Set<string>();
  for (const v of value) {
    if (!v || typeof v !== "object") continue;
    const item = v as Record<string, unknown>;
    const title = typeof item.title === "string" ? item.title.trim() : "";
    const slug =
      typeof item.slug === "string" ? item.slug.trim().toLowerCase() : "";
    const body = typeof item.body === "string" ? item.body : "";
    if (!title || !slug) continue;
    // Only safe URL-safe slugs (lowercase + dashes) — never external paths.
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) continue;
    if (seen.has(slug)) continue;
    seen.add(slug);
    out.push({ slug, title, body });
  }
  return out.length ? out : null;
}

function asNavLinks(value: unknown): LandingNavLink[] | null {
  if (!Array.isArray(value)) return null;
  const out: LandingNavLink[] = [];
  for (const v of value) {
    if (!v || typeof v !== "object") continue;
    const item = v as Record<string, unknown>;
    const label = typeof item.label === "string" ? item.label.trim() : "";
    const href = typeof item.href === "string" ? item.href.trim() : "";
    // Same-app paths only — no javascript: or external URLs.
    if (!label || !href.startsWith("/") || href.includes("://")) continue;
    out.push({ label: label.slice(0, 40), href: href.slice(0, 200) });
  }
  return out.length ? out : null;
}

/**
 * Merge stored content over the compiled defaults field-by-field. Empty/absent
 * values fall back so the public page is never left blank.
 */
export function mergeLandingContent(raw: unknown): LandingContent {
  const d = DEFAULT_LANDING_CONTENT;
  const r = (raw && typeof raw === "object" ? raw : {}) as Record<string, unknown>;

  return {
    heroTitle: asString(r.heroTitle, d.heroTitle),
    heroSubtitle: asString(r.heroSubtitle, d.heroSubtitle),
    heroBadge: asString(r.heroBadge, d.heroBadge),
    featuresHeading: asString(r.featuresHeading, d.featuresHeading),
    featuresSubheading: asString(r.featuresSubheading, d.featuresSubheading),
    features: asFeatures(r.features) ?? d.features,
    howItWorksHeading: asString(r.howItWorksHeading, d.howItWorksHeading),
    howItWorksSubheading: asString(r.howItWorksSubheading, d.howItWorksSubheading),
    howItWorks: asSteps(r.howItWorks) ?? d.howItWorks,
    logoStripHeading: asString(r.logoStripHeading, d.logoStripHeading),
    logos: asLogos(r.logos) ?? d.logos,
    testimonialsHeading: asString(r.testimonialsHeading, d.testimonialsHeading),
    testimonials: asTestimonials(r.testimonials) ?? d.testimonials,
    faqHeading: asString(r.faqHeading, d.faqHeading),
    faqs: asFaqs(r.faqs) ?? d.faqs,
    pricingHeading: asString(r.pricingHeading, d.pricingHeading),
    pricingSubheading: asString(r.pricingSubheading, d.pricingSubheading),
    plans: asPlans(r.plans) ?? d.plans,
    hubsHeading: asString(r.hubsHeading, d.hubsHeading),
    hubsSubheading: asString(r.hubsSubheading, d.hubsSubheading),
    hubs: asHubs(r.hubs) ?? d.hubs,
    ctaTitle: asString(r.ctaTitle, d.ctaTitle),
    ctaSubtitle: asString(r.ctaSubtitle, d.ctaSubtitle),
    ctaButton: asString(r.ctaButton, d.ctaButton),
    pages: asPages(r.pages) ?? d.pages,
    navLinks: asNavLinks(r.navLinks) ?? d.navLinks,
  };
}

