import { createServiceClient } from "@/lib/supabase/server";

// ============================================================================
// Landing page content model
//
// The public marketing page (/ ) reads from site_settings.landing_content,
// falling back to the compiled defaults below whenever a field is missing or
// the column is null. The super admin edits all of this in the visual page
// builder at /dashboard/admin/page-builder.
// ============================================================================

export interface LandingLogo {
  name: string;
  url: string;
  href?: string;
}

export interface LandingFeature {
  title: string;
  description: string;
}

export interface LandingStep {
  step: string;
  title: string;
  description: string;
}

export interface LandingTestimonial {
  quote: string;
  author: string;
}

export interface LandingFaq {
  q: string;
  a: string;
}

export interface LandingContent {
  heroTitle: string;
  heroSubtitle: string;
  heroBadge: string;
  featuresHeading: string;
  featuresSubheading: string;
  features: LandingFeature[];
  howItWorksHeading: string;
  howItWorksSubheading: string;
  howItWorks: LandingStep[];
  logoStripHeading: string;
  logos: LandingLogo[];
  testimonialsHeading: string;
  testimonials: LandingTestimonial[];
  faqHeading: string;
  faqs: LandingFaq[];
  ctaTitle: string;
  ctaSubtitle: string;
  ctaButton: string;
}

/** The compiled-in defaults the landing page ships with. */
export const DEFAULT_LANDING_CONTENT: LandingContent = {
  heroTitle: "The All-in-One Platform for Digital Agencies",
  heroSubtitle:
    "AI-powered content creation, white-label client portals, SEO campaign proposals, social media scheduling, and billing — all in one platform.",
  heroBadge: "14-day free trial · No credit card required · Cancel anytime",
  featuresHeading: "Everything You Need to Run Your Agency",
  featuresSubheading:
    "One platform that replaces 6+ tools. Save time, reduce costs, and deliver better results for your clients.",
  features: [
    {
      title: "AI Content Generation",
      description:
        "Blog posts, social captions, and SEO proposals generated by AI using your own API keys.",
    },
    {
      title: "White-Label Portals",
      description:
        "Each client gets their own branded portal to review and approve content.",
    },
    {
      title: "Content Calendar",
      description:
        "Schedule and manage all your content across platforms in one view.",
    },
    {
      title: "Multi-Tenant Security",
      description:
        "Each agency is fully isolated. Your data, your keys, your clients.",
    },
    {
      title: "Automated Publishing",
      description:
        "Connect social accounts and blog platforms — publish directly from the platform.",
    },
    {
      title: "Team Collaboration",
      description:
        "Agency admins, editors, and clients all have role-based access.",
    },
  ],
  howItWorksHeading: "How it works",
  howItWorksSubheading: "From signup to your first published post in three steps.",
  howItWorks: [
    {
      step: "01",
      title: "Add your API key",
      description:
        "Bring your own OpenAI, DeepSeek, or other API key. Your data stays yours and your AI spend is predictable.",
    },
    {
      step: "02",
      title: "Create a workspace",
      description:
        "Set up a workspace per client with brand voice, knowledge base, and publishing connections.",
    },
    {
      step: "03",
      title: "Generate & publish",
      description:
        "Generate blog posts, social captions, and SEO proposals — then schedule and publish from one calendar.",
    },
  ],
  logoStripHeading: "Trusted by growing agencies",
  logos: [],
  testimonialsHeading: "What agencies are saying",
  testimonials: [],
  faqHeading: "Frequently asked questions",
  faqs: [
    {
      q: "Do I need my own AI API key?",
      a: "Content generation uses your own OpenAI, DeepSeek, or compatible API keys so you control cost and data. The SEO audit tool runs on our platform and needs no key.",
    },
    {
      q: "Is my client data isolated?",
      a: "Yes. Every agency is a fully isolated tenant. Your clients, content, and API keys are never shared with other tenants.",
    },
    {
      q: "What does the 14-day free trial include?",
      a: "Full access to every feature on your chosen plan. No credit card required. Upgrade or cancel anytime.",
    },
    {
      q: "Can I white-label the portal for my clients?",
      a: "Yes. Each client gets a branded portal to review and approve content — no Agency OS branding required.",
    },
  ],
  ctaTitle: "Ready to Scale Your Agency?",
  ctaSubtitle:
    "Replace your content tool stack with one platform. Start your 14-day free trial today.",
  ctaButton: "Get Started Free",
};

// ---------------------------------------------------------------------------
// Sanitization — never trust DB content when rendering the public page.
// ---------------------------------------------------------------------------

function asString(value: unknown, fallback: string): string {
  return typeof value === "string" && value.trim().length > 0
    ? value.trim()
    : fallback;
}

function asStringArray(value: unknown): string[] | null {
  if (!Array.isArray(value)) return null;
  const out: string[] = [];
  for (const v of value) {
    if (typeof v === "string" && v.trim()) out.push(v.trim());
  }
  return out.length ? out : null;
}

function asFeatures(value: unknown): LandingFeature[] | null {
  if (!Array.isArray(value)) return null;
  const out: LandingFeature[] = [];
  for (const v of value) {
    if (!v || typeof v !== "object") continue;
    const item = v as Record<string, unknown>;
    const title = typeof item.title === "string" ? item.title.trim() : "";
    const description =
      typeof item.description === "string" ? item.description.trim() : "";
    if (title) out.push({ title, description });
  }
  return out.length ? out : null;
}

function asSteps(value: unknown): LandingStep[] | null {
  if (!Array.isArray(value)) return null;
  const out: LandingStep[] = [];
  for (const v of value) {
    if (!v || typeof v !== "object") continue;
    const item = v as Record<string, unknown>;
    const title = typeof item.title === "string" ? item.title.trim() : "";
    if (!title) continue;
    out.push({
      step: typeof item.step === "string" ? item.step.trim() : "",
      title,
      description:
        typeof item.description === "string" ? item.description.trim() : "",
    });
  }
  return out.length ? out : null;
}

function asLogos(value: unknown): LandingLogo[] | null {
  if (!Array.isArray(value)) return null;
  const out: LandingLogo[] = [];
  for (const v of value) {
    if (!v || typeof v !== "object") continue;
    const item = v as Record<string, unknown>;
    const name = typeof item.name === "string" ? item.name.trim() : "";
    const url = typeof item.url === "string" ? item.url.trim() : "";
    if (!url) continue;
    out.push({
      name: name || url,
      url,
      href: typeof item.href === "string" ? item.href.trim() : undefined,
    });
  }
  return out.length ? out : null;
}

function asTestimonials(value: unknown): LandingTestimonial[] | null {
  if (!Array.isArray(value)) return null;
  const out: LandingTestimonial[] = [];
  for (const v of value) {
    if (!v || typeof v !== "object") continue;
    const item = v as Record<string, unknown>;
    const quote = typeof item.quote === "string" ? item.quote.trim() : "";
    if (!quote) continue;
    out.push({
      quote,
      author: typeof item.author === "string" ? item.author.trim() : "",
    });
  }
  return out.length ? out : null;
}

function asFaqs(value: unknown): LandingFaq[] | null {
  if (!Array.isArray(value)) return null;
  const out: LandingFaq[] = [];
  for (const v of value) {
    if (!v || typeof v !== "object") continue;
    const item = v as Record<string, unknown>;
    const q = typeof item.q === "string" ? item.q.trim() : "";
    if (!q) continue;
    out.push({ q, a: typeof item.a === "string" ? item.a.trim() : "" });
  }
  return out.length ? out : null;
}

/**
 * Merge stored content over the compiled defaults field-by-field. Empty/absent
 * values fall back so the public page is never left blank.
 */
export function mergeLandingContent(raw: unknown): LandingContent {
  const d = DEFAULT_LANDING_CONTENT;
  const r = (raw && typeof raw === "object" ? raw : {}) as Record<string, unknown>;

  return {
    heroTitle: asString(r.heroTitle, d.heroTitle),
    heroSubtitle: asString(r.heroSubtitle, d.heroSubtitle),
    heroBadge: asString(r.heroBadge, d.heroBadge),
    featuresHeading: asString(r.featuresHeading, d.featuresHeading),
    featuresSubheading: asString(r.featuresSubheading, d.featuresSubheading),
    features: asFeatures(r.features) ?? d.features,
    howItWorksHeading: asString(r.howItWorksHeading, d.howItWorksHeading),
    howItWorksSubheading: asString(r.howItWorksSubheading, d.howItWorksSubheading),
    howItWorks: asSteps(r.howItWorks) ?? d.howItWorks,
    logoStripHeading: asString(r.logoStripHeading, d.logoStripHeading),
    logos: asLogos(r.logos) ?? d.logos,
    testimonialsHeading: asString(r.testimonialsHeading, d.testimonialsHeading),
    testimonials: asTestimonials(r.testimonials) ?? d.testimonials,
    faqHeading: asString(r.faqHeading, d.faqHeading),
    faqs: asFaqs(r.faqs) ?? d.faqs,
    ctaTitle: asString(r.ctaTitle, d.ctaTitle),
    ctaSubtitle: asString(r.ctaSubtitle, d.ctaSubtitle),
    ctaButton: asString(r.ctaButton, d.ctaButton),
  };
}

/**
 * Server-side loader for the public landing page. Never throws — on any error
 * it returns the compiled defaults so the marketing site always renders.
 */
export async function getLandingContent(): Promise<LandingContent> {
  try {
    const supabase = await createServiceClient();
    const { data } = await supabase
      .from("site_settings")
      .select("landing_content")
      .eq("id", 1)
      .maybeSingle();
    return mergeLandingContent(data?.landing_content);
  } catch {
    return DEFAULT_LANDING_CONTENT;
  }
}
