import { inflateRawSync } from "node:zlib";

/**
 * Dependency-free text extraction for PDF uploads to the knowledge base.
 *
 * PDFs are complex, but the vast majority of text-based PDFs (generated by
 * Word, Google Docs, browsers, etc.) store their text in *content streams*
 * that are FlateDecode-compressed and contain text-showing operators:
 *
 *   (some text) Tj
 *   [(a) (b)] TJ
 *
 * This walks every `stream ... endstream` body in the file, tries to inflate
 * it raw (FlateDecode), and pulls the parenthesised strings out of those
 * operators. It is deliberately heuristic — scanned/image-only PDFs yield no
 * text (extracted=false) and are stored but not parsed, exactly like the DOCX
 * path. It never throws on malformed input.
 */

// ---------------------------------------------------------------------------
// Raw PDF stream scanning
// ---------------------------------------------------------------------------

function collectStreams(buf: Buffer): Buffer[] {
  const streams: Buffer[] = [];
  const marker = Buffer.from("stream");
  const endMarker = Buffer.from("endstream");

  let cursor = 0;
  // Streams are introduced by `stream\r\n`, `stream\n`, or `stream\r` — the
  // keyword must be followed by an EOL to avoid matching "streamX".
  while (cursor < buf.length) {
    const start = buf.indexOf(marker, cursor);
    if (start < 0) break;
    const after = start + marker.length;
    let dataStart = after;
    if (buf[after] === 0x0d && buf[after + 1] === 0x0a) dataStart = after + 2;
    else if (buf[after] === 0x0a || buf[after] === 0x0d) dataStart = after + 1;

    const end = buf.indexOf(endMarker, dataStart);
    if (end < 0) break;
    // Strip the trailing EOL before `endstream`.
    let dataEnd = end;
    if (buf[dataEnd - 1] === 0x0a) dataEnd -= 1;
    if (buf[dataEnd - 1] === 0x0d) dataEnd -= 1;

    if (dataEnd > dataStart) streams.push(buf.subarray(dataStart, dataEnd));
    cursor = end + endMarker.length;
  }
  return streams;
}

// ---------------------------------------------------------------------------
// Content-stream text operators
// ---------------------------------------------------------------------------

/** Decode a PDF literal string `(...)` — handles escapes and octal codes. */
function decodePdfString(raw: string): string {
  let out = "";
  for (let i = 0; i < raw.length; i++) {
    const ch = raw[i];
    if (ch === "\\") {
      const next = raw[i + 1];
      if (next === "n") { out += "\n"; i++; continue; }
      if (next === "r") { out += "\r"; i++; continue; }
      if (next === "t") { out += "\t"; i++; continue; }
      if (next === "b") { out += "\b"; i++; continue; }
      if (next === "f") { out += "\f"; i++; continue; }
      if (next === "(") { out += "("; i++; continue; }
      if (next === ")") { out += ")"; i++; continue; }
      if (next === "\\") { out += "\\"; i++; continue; }
      // Octal escape \ddd
      if (next && /[0-7]/.test(next)) {
        const digits = raw.slice(i + 1, i + 4).match(/^[0-7]{1,3}/)?.[0] ?? "";
        out += String.fromCharCode(parseInt(digits, 8));
        i += digits.length;
        continue;
      }
      i++; // unknown escape — skip the backslash
      continue;
    }
    out += ch;
  }
  return out;
}

/**
 * Extract text from a single content stream. Handles `(...) Tj` and
 * `[(...) (...)] TJ`. Text bytes are decoded as WinAnsi (close enough to
 * Latin-1 for the common case; genuine CID fonts won't decode, which is
 * acceptable for a best-effort extractor).
 */
function extractTextFromContent(stream: Buffer): string {
  const src = stream.toString("latin1");
  const chunks: string[] = [];

  let i = 0;
  const len = src.length;
  while (i < len) {
    const ch = src[i];
    if (ch === "(") {
      // Scan to the matching unescaped close paren.
      let j = i + 1;
      let depth = 1;
      let raw = "";
      while (j < len && depth > 0) {
        const c = src[j];
        if (c === "\\") {
          raw += c + (src[j + 1] ?? "");
          j += 2;
          continue;
        }
        if (c === "(") depth++;
        if (c === ")") depth--;
        if (depth > 0) raw += c;
        j++;
      }
      chunks.push(decodePdfString(raw));
      i = j;
      continue;
    }
    i++;
  }

  return chunks.join("");
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface ExtractedPdf {
  text: string;
  extracted: boolean;
}

/** Best-effort PDF text extraction. Returns { text, extracted:false } when the
 *  PDF is scanned/image-only or otherwise unparseable. */
export function extractPdfText(buffer: Buffer): ExtractedPdf {
  try {
    const streams = collectStreams(buffer);
    const parts: string[] = [];
    for (const stream of streams) {
      let data: Buffer;
      try {
        data = inflateRawSync(stream); // FlateDecode
      } catch {
        data = stream; // stored uncompressed
      }
      const text = extractTextFromContent(data).trim();
      if (text) parts.push(text);
    }
    const text = parts.join("\n\n").replace(/\n{3,}/g, "\n\n").trim();
    return { text, extracted: text.length > 0 };
  } catch {
    return { text: "", extracted: false };
  }
}
