import { notFound } from "next/navigation";
import { createServiceClient } from "@/lib/supabase/server";
import {
  renderBlockHtml,
  CMS_STYLES,
  CMS_HEADER_FOOTER_STYLES,
  THEME_PRESETS,
  type CmsBlock,
} from "@/lib/cms";

// Must be request-time rendered: pages are read from the DB per slug, and
// notFound() must return a real 404 (static prerender returns 200 here).
export const dynamic = "force-dynamic";

/**
 * Public CMS renderer — /site/<slug>.
 * Renders a published page's blocks wrapped in the tenant's sitewide header
 * and footer, with the chosen theme preset + custom global stylesheet applied.
 * Unpublished pages 404 publicly UNLESS a matching ?preview=<token> is given
 * (draft-preview links generated by the Web Builder).
 */
export default async function SitePage({
  params,
  searchParams,
}: {
  params: Promise<{ slug: string }>;
  searchParams: Promise<{ preview?: string }>;
}) {
  const { slug } = await params;
  const { preview } = await searchParams;
  const supabase = await createServiceClient();

  const { data: page, error } = await supabase
    .from("site_pages")
    .select("id, title, blocks, is_published, preview_token, tenant_id, kind, category")
    .eq("slug", slug)
    .maybeSingle();

  if (error || !page) {
    notFound();
  }

  // Draft pages require the secret preview token.
  if (!page.is_published) {
    if (!preview || !page.preview_token || preview !== page.preview_token) {
      notFound();
    }
  }

  // Sitewide settings for this tenant (header/footer + theme). Defaults when
  // no row exists yet.
  const { data: site } = await supabase
    .from("cms_site_settings")
    .select("site_name, tagline, logo_url, header_blocks, footer_blocks, site_nav, global_css, theme_preset")
    .eq("tenant_id", page.tenant_id)
    .maybeSingle();

  const siteName = site?.site_name || "My Site";
  const tagline = site?.tagline || "";
  const presetCss = THEME_PRESETS[site?.theme_preset as string]?.css ?? THEME_PRESETS.clean.css;
  const globalCss = site?.global_css || "";

  const headerBlocks = (Array.isArray(site?.header_blocks) ? site.header_blocks : []) as CmsBlock[];
  const footerBlocks = (Array.isArray(site?.footer_blocks) ? site.footer_blocks : []) as CmsBlock[];
  // Site menu (ordered nav links set in the Web Builder's Site Settings).
  const siteNav = (Array.isArray(site?.site_nav) ? site.site_nav : []).filter(
    (n): n is { label: string; href: string } =>
      !!n && typeof n.label === "string" && !!n.label && typeof n.href === "string" && !!n.href
  );
  const navHref = (href: string) =>
    /^https?:\/\//.test(href) ? href : `/site/${href.replace(/^\/site\//, "")}`;

  const renderBlocks = (blocks: CmsBlock[]) =>
    blocks.map((b) => renderBlockHtml(b, page.id)).join("\n");

  // Blog archive pages: list published blog_post pages from the same tenant.
  let archivePosts: { slug: string; title: string; category: string | null; created_at: string | null }[] = [];
  if (page.kind === "blog_archive") {
    const { data: posts } = await supabase
      .from("site_pages")
      .select("slug, title, category, created_at")
      .eq("tenant_id", page.tenant_id)
      .eq("kind", "blog_post")
      .eq("is_published", true)
      .order("created_at", { ascending: false })
      .limit(100);
    archivePosts = (posts ?? []) as typeof archivePosts;
  }

  const blocks = (Array.isArray(page.blocks) ? page.blocks : []) as CmsBlock[];
  const html = renderBlocks(blocks);

  return (
    <html>
      <head>
        <title>{page.title} — {siteName}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style dangerouslySetInnerHTML={{ __html: `${CMS_STYLES}\n${CMS_HEADER_FOOTER_STYLES}\n${presetCss}\n${globalCss}` }} />
      </head>
      <body style={{ margin: 0, background: "#fff" }}>
        {/* Sitewide header */}
        <header className="cms-site-header">
          <div>
            {site?.logo_url ? (
              <img src={site.logo_url} alt={siteName} className="cms-site-logo" />
            ) : (
              <span className="cms-site-name">{siteName}</span>
            )}
            {tagline && <span className="cms-site-tagline"> — {tagline}</span>}
          </div>
          {siteNav.length > 0 && (
            <nav className="cms-site-nav" aria-label="Site navigation">
              {siteNav.map((item, i) => (
                <a key={i} href={navHref(item.href)}>{item.label}</a>
              ))}
            </nav>
          )}
          {headerBlocks.length > 0 && (
            <div dangerouslySetInnerHTML={{ __html: renderBlocks(headerBlocks) }} />
          )}
        </header>

        <div className="cms-shell">
          {page.kind === "blog_archive" && archivePosts.length > 0 ? (
            <ul className="cms-archive">
              {archivePosts.map((p) => (
                <li key={p.slug}>
                  <a href={`/site/${p.slug}`}>
                    <span className="cms-archive-title">{p.title}</span>
                    {p.category && <span className="cms-archive-cat">{p.category}</span>}
                  </a>
                </li>
              ))}
            </ul>
          ) : (
            <div dangerouslySetInnerHTML={{ __html: html }} />
          )}
        </div>

        {/* Sitewide footer */}
        {footerBlocks.length > 0 && (
          <footer className="cms-site-footer">
            <div dangerouslySetInnerHTML={{ __html: renderBlocks(footerBlocks) }} />
          </footer>
        )}

        {/* Form widgets submit via fetch so the page doesn't navigate away. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
document.addEventListener('submit', (e) => {
  const f = e.target;
  if (!f.classList.contains('cms-form')) return;
  e.preventDefault();
  const status = f.querySelector('.cms-form-status');
  const data = new FormData(f);
  data.set('page_id', f.dataset.page || '');
  data.set('block_id', f.dataset.block || '');
  fetch(f.getAttribute('action') || '/api/cms/forms', { method: 'POST', body: data })
    .then(r => r.json().catch(() => ({})))
    .then(d => { if (status) { status.className = 'cms-form-status ' + (d.success ? 'ok' : 'err'); status.textContent = d.success ? d.message : (d.error || 'Something went wrong.'); } })
    .catch(() => { if (status) { status.className = 'cms-form-status err'; status.textContent = 'Network error.'; } });
});
`,
          }}
        />
      </body>
    </html>
  );
}
